HAI

I HAS A VAR ITZ 1

IM IN YR LOOP UPPIN YR VAR
  BOTH SAEM VAR AN 101, O RLY?
    YA RLY, GTFO
  OIC
  
  BOTH SAEM MOD OF VAR AN 15 AN 0, O RLY?
    YA RLY, VISIBLE "FIZZBUZZ"
    MEBBE BOTH SAEM MOD OF VAR AN 3 AN 0, VISIBLE "FIZZ"
    MEBBE BOTH SAEM MOD OF VAR AN 5 AN 0, VISIBLE "BUZZ"
    NO WAI, VISIBLE VAR
  OIC
IM OUTTA YR LOOP

KTHXBYE